core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('signup/', views.CreateNewUser.as_view(), name='create-user'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('users_list/', views.UsersListView.as_view(), name='users-list'),
    path('thank_you/', views.thank_you, name='thank-you')
]

dog_show/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('exibition.urls')),
    path('user/', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

exibition/urls.py
from django.urls import path
from . import views

app_name = 'exibition'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('thank_you/', views.thank_you, name='thank-you'),
    path('owner/', views.OwnerList.as_view(), name='owner-list'),
    path('owner_create/', views.OwnerCreateView.as_view(), name='owner-create'),
    path('owner_update/<int:pk>',
         views.OwnerUpdateView.as_view(), name='owner-update'),
    path('owner_delete/<int:pk>',
         views.OwnerDeleteView.as_view(), name='owner-delete'),
    path('owner/<int:pk>/', views.OwnerDetailView.as_view(), name='owner-detail'),
    path('breed/', views.BreedList.as_view(), name='breed-list'),
    path('breed_create/', views.BreedCreateView.as_view(), name='breed-create'),
    path('breed_update/<int:pk>',
         views.BreedUpdateView.as_view(), name='breed-update'),
    path('breed_delete/<int:pk>',
         views.BreedDeleteView.as_view(), name='breed-delete'),
    path('breed/<int:pk>/', views.BreedDetailView.as_view(), name='breed-detail'),
    path('dogs/', views.DogList.as_view(), name='dog-list'),
    path('dog_create/', views.DogCreateView.as_view(), name='dog-create'),
    path('dog_update/<int:pk>',
         views.DogUpdateView.as_view(), name='dog-update'),
    path('dog_delete/<int:pk>',
         views.DogDeleteView.as_view(), name='dog-delete'),
    path('dogs/<int:pk>/', views.DogDetailView.as_view(), name='dog-detail'),
    path('judges/', views.JudgeList.as_view(), name='judge-list'),
    path('shows/', views.ShowList.as_view(), name='show-list'),
    path('sponsors/', views.SponsorList.as_view(), name='sponsor-list'),
]

exibition/models.py
from django.conf import settings
from django.db import models


class Owner(models.Model):
    phone = models.PositiveSmallIntegerField(blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.user.first_name} {self.user.last_name}'


class Breed(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self) -> str:
        return self.name


class Dog(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female')
    ]
    name = models.CharField(max_length=255)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    age = models.IntegerField()
    weight = models.PositiveSmallIntegerField()
    color = models.CharField(max_length=255)
    owner = models.ForeignKey(
        Owner, on_delete=models.CASCADE, related_name='dogs')
    breed = models.ForeignKey(
        Breed, on_delete=models.PROTECT, related_name='dogs_breed')
    image = models.ImageField(
        upload_to='exibition/images', null=True, blank=True)

    def __str__(self) -> str:
        return f'{self.breed} - {self.name}'


class Sponsor(models.Model):
    name = models.CharField(max_length=255)
    contact_person = models.CharField(max_length=255)
    contact_email = models.EmailField(unique=True)
    contact_phone = models.PositiveSmallIntegerField()

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.name


class Show(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField()
    sponsor = models.ForeignKey(
        Sponsor, on_delete=models.SET_NULL, null=True, related_name='shows')

    def __str__(self) -> str:
        return f'{self.name} - {self.location}'


class Judge(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = models.PositiveSmallIntegerField()

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

exibition/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.http import Http404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Breed, Dog, Owner, Judge, Show, Sponsor


class HomeView(TemplateView):
    template_name = 'exibition/home.html'


class OwnerList(ListView):
    model = Owner
    template_name = 'exibition/owner_list.html'
    context_object_name = 'owners'


def thank_you(request):
    return render(request, 'exibition/thank_you.html')


class OwnerDetailView(DetailView):
    model = Owner
    template_name = 'exibition/owner_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        owner = self.get_object()
        context["dogs"] = Dog.objects.filter(owner=owner)
        return context


class OwnerCreateView(LoginRequiredMixin, CreateView):
    model = Owner
    fields = ['first_name', 'last_name', 'email',
              'phone', 'address', 'user']
    success_url = reverse_lazy('exibition:thank-you')

    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.is_authenticated:
    #         raise Http404("You must be logged in to access this page.")
    #     return super().dispatch(request, *args, **kwargs)


class OwnerUpdateView(LoginRequiredMixin, UpdateView):
    model = Owner
    fields = fields = ['first_name', 'last_name',
                       'email', 'phone', 'address', 'user']
    success_url = reverse_lazy('exibition:owner-list')


class OwnerDeleteView(LoginRequiredMixin, DeleteView):
    model = Owner
    success_url = reverse_lazy('exibition:owner-list')


class BreedList(ListView):
    model = Breed
    template_name = 'exibition/breed_list.html'
    context_object_name = 'breeds'


class BreedDetailView(DetailView):
    model = Breed


class BreedCreateView(LoginRequiredMixin, CreateView):
    model = Breed
    fields = ['name', 'description']
    success_url = reverse_lazy('exibition:thank-you')


class BreedUpdateView(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = ['name', 'description']
    success_url = reverse_lazy('exibition:breed-list')


class BreedDeleteView(LoginRequiredMixin, DeleteView):
    model = Breed
    success_url = reverse_lazy('exibition:breed-list')


class DogList(ListView):
    model = Dog
    template_name = 'exibition/dog_list'
    context_object_name = 'dogs'


class DogDetailView(DetailView):
    model = Dog


class DogCreateView(LoginRequiredMixin, CreateView):
    model = Dog
    fields = ['name', 'breed', 'gender', 'age',
              'weight', 'color', 'owner', 'breed', 'image']
    success_url = reverse_lazy('exibition:thank-you')


class DogUpdateView(LoginRequiredMixin, UpdateView):
    model = Dog
    fields = ['name', 'breed', 'gender', 'age',
              'weight', 'color', 'owner', 'breed', 'image']
    success_url = reverse_lazy('exibition:dog-list')


class DogDeleteView(LoginRequiredMixin, DeleteView):
    model = Dog
    fields = ['name', 'breed', 'gender', 'age',
              'weight', 'color', 'owner', 'breed']
    success_url = reverse_lazy('exibition:dog-list')


class JudgeList(ListView):
    model = Judge
    template_name = 'exibition/judge_list'
    context_object_name = 'judges'


class ShowList(ListView):
    model = Show
    template_name = 'exibition/show_list'
    context_object_name = 'shows'


class SponsorList(ListView):
    model = Sponsor
    template_name = 'exibition/sponsor_list'
    context_object_name = 'sponsors'

exibition/templates/exibition/breed_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>Detail view for breed {{breed}}</h2>
    <hr>
    <h5>{{ breed.description|truncatewords:50 }}</h5>

{% endblock content %}

exibition/templates/exibition/breed_form.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='Submit'>

    </form>
{% endblock content %}

exibition/templates/exibition/breed_list.html
{% extends "base.html" %}
{% block content %}
<button><a href="{% url 'exibition:breed-create' %}">Add new Breed</a></button>
<br>
<hr>
<h5>List of breeds:</h5>
<hr>
<ul>
{% for breed in object_list %}
    <li>
        <a href="{% url 'exibition:breed-detail' breed.id %}">{{ breed.name }}</a>
        <ul>
            <li><a href="{% url 'exibition:breed-update' breed.pk %}">Update Info</a></li>
            <li><a href="{% url 'exibition:breed-delete' breed.pk %}">Delete Breed {{breed.name}}</a></li>
        </ul>
    </li>


{% endfor %}
</ul>
{% endblock content %}

exibition/templates/exibition/dog_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2>Are you sure you want to delete dog {{dog.name}} - {{ dog.breed }}?</h2>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value='Confirm delete'>
    
    <button><a href="{% url 'exibition:dog-list' %}">Back</a></button>

</form>

{% endblock content %}

exibition/templates/exibition/dog_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>Detail for dog number {{dog.id}}:</h2>
    <hr>
    <ul>
        <li>Name: {{ dog.name }} - {{ dog.breed }} - Gender: {{ dog.gender }} - Age: {{ dog.age }} - Weight {{ dog.weight }}kg.</li>
        <img  src="{{ dog.image.url }}" alt="{{ dog.name }}" style="max-width: 300px;">
    </ul>
{% endblock content %}

exibition/templates/exibition/dog_form.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='Submit'>

    </form>
{% endblock content %}

exibition/templates/exibition/dog_list.html
{% extends "base.html" %}
{% block content %}
<button><a href="{% url 'exibition:dog-create' %}">Add new Dog</a></button>
<br>
<hr>
<h5>List of dogs:</h5>
<hr>
<ul>
{% for dog in dogs %}

    <li>
        <a href="{% url 'exibition:dog-detail' dog.id %}">{{ dog.name }} - {{ dog.breed }} </a>
        <ul>
            <li><a href="{% url 'exibition:dog-update' dog.id %}">Update Info</a></li>
            <li><a href="{% url 'exibition:dog-delete' dog.pk %}">Delete Dog: {{dog.name}} - {{dog.breed}}</a></li>
        </ul> 
    </li>




{% endfor %}
</ul>

{% endblock content %}

exibition/templates/exibition/home.html
{% extends "base.html" %}
{% block title %}
<title>Home</title>
{% endblock title %}
{% block content %}
<br>
<h1>WELCOME TO DOG SHOW!</h1>
<br>
<hr>
<br>
<h3>Enjoy everyone :-)</h3>
{% endblock content %}

exibition/templates/exibition/owner_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2>Are you sure you want to delete owner {{owner}}?</h2>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value='Confirm delete'>

</form>

{% endblock content %}

exibition/templates/exibition/owner_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>Detail view for owner number {{owner.id}}:</h2>
    <hr>
    <h5>{{ owner }} presents his dog:</h5>

    <ul>
    {% for dog in dogs %}
    <br>
        <li>{{ dog.breed }} - {{ dog.name }}</li>
    {% endfor %}
    </ul>
{% endblock content %}

exibition/templates/exibition/owner_form.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='Submit'>

    </form>
{% endblock content %}

exibition/templates/exibition/owner_list.html
{% extends "base.html" %}
{% block content %}
<button><a href="{% url 'exibition:owner-create' %}">Add new Owner</a></button>
<br>
<hr>
<h5>List of owners:</h5>
<hr>
<ul>
{% for owner in owners %}
<li>
    <a href="{% url 'exibition:owner-detail' owner.id %}">{{ owner.user.first_name }} {{ owner.user.last_name }}</a>
    <ul>
        <li><a href="{% url 'exibition:owner-update' owner.id %}">Update Info for {{ owner.user.first_name }}</a></li>
        <li><a href="{% url 'exibition:owner-delete' owner.id %}">Delete Owner '{{ owner.user.first_name }}'</a></li>
    </ul>
</li>

{% endfor %}
</ul>



{% endblock content %}

exibition/templates/exibition/show_list.html
{% extends "base.html" %}
{% block content %}
<br>
<hr>
{% for show in shows %}
<ul>
    <li>{{ show.name }} - {{ show.location }}</li>
</ul>

{% endfor %}

{% endblock content %}

exibition/templates/exibition/sponsor_list.html
{% extends "base.html" %}
{% block content %}
<br>
<hr>
{% for sponsor in sponsors %}
<ul>
    <li>{{ sponsor.name }}</li>
</ul>

{% endfor %}

{% endblock content %}