core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('signup/', views.CreateNewUser.as_view(), name='create-user'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('users_list/', views.UsersListView.as_view(), name='users-list'),
    path('thank_you/', views.thank_you, name='thank-you')
]

dog_show/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('exibition.urls')),
    path('user/', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

exibition/urls.py
from django.urls import path
from . import views

app_name = 'exibition'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('thank_you/', views.thank_you, name='thank-you'),
    path('owner/', views.OwnerList.as_view(), name='owner-list'),
    path('owner_create/', views.OwnerCreateView.as_view(), name='owner-create'),
    path('owner_update/<int:pk>',
         views.OwnerUpdateView.as_view(), name='owner-update'),
    path('owner_delete/<int:pk>',
         views.OwnerDeleteView.as_view(), name='owner-delete'),
    path('owner/<int:pk>/', views.OwnerDetailView.as_view(), name='owner-detail'),
    path('breed/', views.BreedList.as_view(), name='breed-list'),
    path('breed_create/', views.BreedCreateView.as_view(), name='breed-create'),
    path('breed_update/<int:pk>',
         views.BreedUpdateView.as_view(), name='breed-update'),
    path('breed_delete/<int:pk>',
         views.BreedDeleteView.as_view(), name='breed-delete'),
    path('breed/<int:pk>/', views.BreedDetailView.as_view(), name='breed-detail'),
    path('dogs/', views.DogList.as_view(), name='dog-list'),
    path('dog_create/', views.DogCreateView.as_view(), name='dog-create'),
    path('dog_update/<int:pk>',
         views.DogUpdateView.as_view(), name='dog-update'),
    path('dog_delete/<int:pk>',
         views.DogDeleteView.as_view(), name='dog-delete'),
    path('dogs/<int:pk>/', views.DogDetailView.as_view(), name='dog-detail'),
    path('judges/', views.JudgeList.as_view(), name='judge-list'),
    path('shows/', views.ShowList.as_view(), name='show-list'),
    path('sponsors/', views.SponsorList.as_view(), name='sponsor-list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block title %}
    
    {% endblock title %}
   
</head>
<body>
  {% if user.is_authenticated %}
  <p>You are logged in as {{ user.username }} 
    <form method="post" action="{% url 'core:logout' %}">
      <button type="submit">Logout</button>
      {% csrf_token %}
  </form>
  <br>


  </p>
  
  {% else %}
  <p>You are not logged in, please <a href="{% url 'core:login' %}">Login</a> or <a href="{% url 'core:create-user' %}">SignUp</a></p>
{% endif %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'exibition:home' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'exibition:show-list' %}">Show</a>
            <a class="nav-item nav-link" href="{% url 'exibition:breed-list' %}">Breed</a>
            <a class="nav-item nav-link" href="{% url 'exibition:owner-list' %}">Owners</a>
            <a class="nav-item nav-link" href="{% url 'exibition:dog-list' %}">All Dogs</a>
            <a class="nav-item nav-link" href="{% url 'exibition:sponsor-list' %}">Sponsors</a>
            <a class="nav-item nav-link" href="{% url 'exibition:judge-list' %}">Judges</a>
            <a class="nav-item nav-link" href="{% url 'core:users-list' %}">Users</a>
          </div>
        </div>
      </nav>
    {% block content %}
    
    {% endblock content %}
        
</body>
</html>